from utils import *
from telebot import util
def test_tocho(message):
    if message.text: return message.text[:6]=='!tocho'

@bot.message_handler(func=test_tocho)
def monumento(message):
    if message.text[:7]=='!tocho ':
        if message.text[7:] in tochos:
            tocho=tochos[message.text[7:]]
            if len(tocho)>3000:
                splitted_tocho=util.split_string(tocho,3000)
                for text in splitted_tocho:
                    bot.send_message(message.chat.id,text)
            else:
                bot.send_message(message.chat.id,tocho,parse_mode="HTML")
    else:
        tocho_list='\n'.join(['%s' % k for k in tochos.keys()])
        bot.send_message(message.chat.id,'<b>Los tochos de forocoches son:</b>\n'+tocho_list,parse_mode="HTML")


tochos={'pc':'''Menudo pc te estas montando, hijo de puta. Te lo estás currando que da gusto. Se te marcan hasta los nucleos con tan sólo 1000€ en componentes. Menudo hijo de puta estás hecho. Sin apenas pagar tienes un puto pc de flipar. Hijo de una perra sarnosa, jodida grafica tienes, todo a 60 fps rocosos sin bajadas. Menudo hijo de la gran puta estás hecho, si te lo curras bien puedes llegar al star citizen en ultra. En tan sólo unas semana ya te has pillado un pc así, no me quiero imaginar dónde estarás dentro de un puto mes. Menudo hijo de puta estás hecho. Te vas a poner del copón, cabronazo. Me encanta la gente como tú que se lo curra tanto. Ánimo. Sigue así, te esta quedando de puta madre, hijo de puta.

Y a los que dicen que es una mierda ni puto caso, son un atajo de mierdas con pentium 1 que solo les gusta jugar al solitario. Tu, sin embargo, estás del copón, hijo de la grandísima puta. Qué suerte tenéis algunos con los componentes.

Saludos y a darle fuerte al 4K, cabronazo.''',
        'maduras':'''Lo mejor de las maduras, es que puedes comerles el roscón de reyes, mientras te tienen al fuego unas lentejas de puta madre. Yo recuerdo una que conocí en un eroski, y la recuerdo como uno de los mejores polvos de mi vida. Ella me hizo unos callos cojonudisisimos, y mientras los preparaba, yo le daba como un cabrón por el ojete, ya que se había puesto faldita para que fuese haciendo mientras cocinaba. Creo que eyaculé tal cantidad de esperma, que estuve dos horas inconsciente. Menos mal que los callos me dieron fuerza para acabar el día con un par más. Y tenía unos hijos majísimos. Menudos vicios echamos al crash bandicoot 2.'''
        ,'spiderman':'''Os cuento, quede con una golfilla para intimar en su pisito, empezamos normal, nos liamos y demas (ella tenia bastante interes en chuparme la oreja, a un rato me dio hasta mal rollo la cabrona). Bueno, yo no lleve cartera y claro, cuando estabamos ya muy cachondos le dije amablamente si tenia condones, me dijo que no...hice como que me molestaba...ella me dijo que yo siempre suelo llevarlos, le dije que se me olvido la cartera y demas...total que accedio a hacer la marcha atras y yo pensando "esta es la mia, le hare el spiderman". Estamos arreando y demas y despues d eun buen rato veo que me voy a correr, saco mi tizona, me corro en mi mano y ella se queda un poco con cara de roto2, y entonces cojo y le tiro la lefada a su cara y le digo "soy spidermaaaaan" y no me esperaba su reaccion, me empezo a llamar hijo de puta, me dio tortazos como loca :S y empezo a decir que no veia, que se lo meti en el ojo, yo viendo el percal me vesti y me fui, luego me llamo y me dijo que era un hijo de puta, yo le dije que era una broma en plan colegas, pero nada, dice que tuvo que ir al medico pasando verguenza porque tenia el ojo muy irritado... y que como volviera a enviarla algo para quedar me denuncia.
Un claro caso de T_D_S P_T_S...que poco sentido del humor.'''
,'braulio':'''Pam pam!!!!! estaba yo ayer ahiii to locooo por la calle dando un paseo ahi to desfasao, y de repente viene una pava y me dices tienes un cigarro y le digoooo un puro habano pa tu boca putaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaa, y se lo tomo a mal, y se lo dijo a un polisia que habia ahi al laooo y el tio me viene y me diseeeee la violamos entre los dos loco loco locooooooooooo y yo joderrrrrrr, que tiene 15 añossss jajajajaa pero al final no era un polisia, era Braulio. Ahsadishaudhusahuhuahua puto Braulio.
Me fui con el de cañas y al final estuvimos ahi to locos tomando mdma hasta que vino una señora y nos dijo payoooos que eso es to malo tomar de esto que es mucho mejor, y nos dio una sopica de ajo to rica jajajajaajahauuahauajaj puta vieja, nos robo la droja y se fue con sus amigas al bingo a ponerse to morá jashajaj.
Arriquitaun taun taun!!!!''',
        'genio':'''Ratatatatatatatapumpumpumpum!!! Estaba yo el otro dia comprando en la mercadona cuando de repente abro una lata de aceitunas porque tenia to el picadon y paaaaaaaaaam aparece un genio que me dice loco loco soy el puto genio de las aceitunas, con una pinta de colgao que flipas yo ya pensaba que se me estaba subiendo el tripi y va el pavo y me dice te concedo tres deseosssss. Y yo buabauabauabauabauaabuaaaaaaa obviamente le pedí un kebap mixto sin verdura y me lo estaba comiendo y de dentro me sale otro genio y yo joder joder un genio moruno y me dice que me concede otros 3 deseos y yo joder joder joderrrrrrrrr, me pare a pensar y dije, cuantos deseos me quedan? digo 5, y de pronto aparese una cajera del mercadona to shula y me dice por el culo te la hinco jajajajaajaja y ahora estoy en el hospital con una fractura anal.
No vuelvo a comprar aceitunas en la puta vida oye.''',
        'guardia civil':'''Te estoy siguiendo de cerca en todos los foros donde anidas, recopilando datos sobre ti incluidas capturas de pantalla como muestras de tus delitos telemáticos, ademas contactando con los administradores de Egela tengo acceso a tu dirección IP la cual reuniré y entregaré como pruebas delante de un juez en el caso de que así se estime. De momento te pongo en preaviso, tengo material suficiente para empapelarte. No sigas por este camino. Te tengo cogido por los huevecillos campeón.''',
        'pipe bender':'''Hola, soy nuevo y no me ubico muxo en esto de los fors, queria saber si alguien sabe como construir una dobladora d etubos(pipe bender), vi que un integrante del foro tenia una antigua, me gustatia saber si puede compartir las dimensiones(un planito), lo d ela bomba se cambia por una gata hidraulica y listo.
Gracias de antemano y muy buen foro''',
        'colon':'''Pues ayer que sali con mis colegas vale y bua estaba con mi morao vale bailando a mi rollo con camiseta de manga corta vale y la verdad es que voy al gimnasio no sigo dietas ni nada de eso porque no me gusta y segundo que no me hace falta aunque reconozco que soy feo vale pero tengo labia entonces cojo vale y eso que se me acaba el cubatica y digo bua loco aora que hago que es pasta y tampoco esta la cosa para ir gastando en bebida vale y cojo y voy a la barra y habia una camarera que estaba muy buena vale y me mira fijamente y le digo sin pensar oye perdona es que se van a pelear y me dice quien??!! y le digo mi poya en tu paladar jaajaaaja se partio el culo riendose mientras le guiñaba el ojo sonriendo vale y le digo como te echo reir enrollate no loca y invitame a un cubatilla ajajaja y se lo dije por decir eh y eso que coje loco y me lo pone jajajaja y me pregunta que de donde soi que nunca me habia visto por ahi pues cojo le explico y eso y le digo que a ver que pasa con su rollo que aber si quedamos fuera sabes y coje y ni corta ni perezosa me dice hoy mismo!bua aqui locos si que flipe ya sabes y bueno pues na se lo dije a los colegas y a la hora de cerrar me espere fuera vale y viene y me dice bueno y a donde vamos y le digo pues nose quieres desayunar algo?puesto que era tarde y me dice dejate de desayunos que a mi me gusta mas pasarla bien buaaaa yo flipando loco pero tenia algo malo todo hay que decirlo y es que era sudamericana vale pero pense en nuestros antepasados en el gran cristobal colon y no podia dejar el liston bajo asi que acabemos en su casa y me imajinaba que era indigena y yo conquistaba su pueblo jajaja alfinal me corri y me fui para casa sabes y con la cabeza alta por nuestras generaciones no descubri america pero si me la folle''',
        'orco':'''Al fin me atrevo a contar aquí la que fue una de las experiencias más demigrantes de mi vida.

Yo tenía 21 años y acababa de dejarlo con mi novia de entonces. Mis amigos decidieron que teníamos que irnos de botellón, como en los viejos tiempos, para olvidar las penas a base de buenos lingotazos de alcohol barato.

Fuimos a Mercadona y adquirimos cuantiosas botellas de Knebep de 3'99€, el vodka más demigrante creado por el ser humano, aunque por aquel entonces todavía llevaba dosificador.

Al fin llegó la hora del botellón y me puse mis mejores galas para estrenar de nuevo la soltería: look pijito con camisa de cuadros bajo un jersey azul marino de cuello de pico, pantalón chino y zapatos oscuros. Esa noche olía a triunfo: aquí y allá bebían grupitos de mozas de culo prieto, con esos vestidos que realzaban sobremanera sus jóvenes curvas. Esa noche debía, por cuestión de honor, conseguir alguno de esos apetecibles pussys, ya que mi ex novia a buen seguro se estaría calzando a esas alturas otro rabo.

Fue uno de esos botellones que a todo el mundo le gustan, donde los cubatas van entrando uno tras otro de descojone en descojone con los colegas. De esos en los que, aunque no fumes, te echas un cigarrito por mera inercia. De esos en los que alguien te dice "no tienes huevos a beberte eso del tirón" y tú te lo tomas como una afrenta personal, y agarras el vaso de tubo lleno de alcohol hasta reventar y en cinco segundos lo has vaciado. De esos en los que le das a probar a alguien de tu cubata y está a poco de echarte la pota encima, aunque para ti ese líquido transparente de tu copa sabe a agua.
-:
El caso es que la noche fue avanzando y el pedal ya era incontrolable. Nunca imaginaría lo que acontecería aquella noche... y si tengo noción de las cosas que pasaron fue gracias a la reconstrucción que mis amigos y yo hicimos los días posteriores... y de lo vivido la mañana siguiente, claro.

Os lo contaré desde lo que yo viví, en primera persona:

Tras hacerse ya muy tarde, todos con un ciego considerable (sobretodo yo), mis amigos decidieron marchar para una discoteca cercana, como mandan los cánones tras todo buen botellón. Yo les seguí y conseguimos pasar dentro gracias a que un amigo conocía al tipo de la puerta. Nuestras condiciones eran de hospital, no de pista de baile.

Tras entrar, fui a la barra a pedir un vodka con naranja... y a partir de ahí todo se hizo oscuro para mi recuerdo y ya no supe nada más...

...hasta la mañana siguiente, claro. Hasta ese día, no fui realmente consciente de que por culpa del alcohol tu cabeza puede generar un lapso de tiempo muy grande sin ningún recuerdo de lo que ha sucedido. De hecho, sólo me ha pasado dos veces, esa y otra más, pero sin duda esa tuvo las consecuencias más demigrantes.

A lo que iba, la mañana siguiente a mi super ciego abrí los ojos. Estaba de lado sobre una cama, tenía un sabor de boca que era mezcla de: vodka barato, vómito, ceniza, sudor. Mi olor era nauseabundo. Un sudor frío recorría mi cabeza y tenía fuertes taquicardias (siempre me han dado con las resacas).

Me di cuenta, tras unos segundos, de que esa no era mi habitación (vivía en un piso de estudiantes con dos amigos) ni mi casa. Lo más llegó cuando haciendo un esfuerzo sobrehumano, pude girar poco a poco la cabeza hacia delante y vi como una jodida gorda estaba a cuatro patas sobre mí lamiéndome el rabo, que por supuesto no reaccionaba de su estado semi-muerto (como lo estaba yo en ese momento).

La gorda vio que me había despertado, me miró a la cara y sonrió con aire de diva, como diciéndose "soy toda una amante, consigo despertarle con mis dotes amatorias". La chica estaba en sujetador y bragas, tenía el típico pelo moreno revuelto (medio rizado medio ondulado) del 99% de las tías y lo que más llamaba la atención eran las lorzacas que se apretaban sobre sí mismas, dándole el aspecto que hubiera tenido la hija guarra del muñeco de Michelin. Lo peor de todo era que, pese a su gordura, estaba plana casi como una tabla de planchar. Pude acertar a ver que sus pechos eran dos tímidas plastas de grasa que apenas conseguían abultar en el sujetador.

No pude evitar el susto y me incorporé un poco sobre la cama. Un zumbido como el de un F1 empezó a martillearme la cabeza. Ella también se incorporó sobre sus rodillas.

-Hola guapo... ¿vaya nochecita, eh?

Mi cara de tuvo que ser épica. Creía que no recordar nada de una borrachera y despertar junto a una gorda demigrante sólo sucedía en las películas.

La saludé tímidamente y empezó a reírse. Esa risa no la olvidaré en la vida shurmanos, la risa de los rechazados, de los personajes peculiares, de las mujeres inseguras que han conocido a pocos hombres... una risa que helaba la sangre.

-Ayer no eras tan tímido -me soltó la tipa.

No me dejaba de preguntar cómo cojones habría llegado a casa de la gorda y qué había hecho con ella, hasta que me incorporé del todo y vi dos envoltorios de condones junto a la cama. Además, la habitación tenía ese olor dulzón a sexo y sudor. Por la sonrisa de la mordoriana pude adivinar que me la había fockado, o que más bien me había fockado ella... o violado, o aprovechado de mi, o como queráis llamarlo.

El zumbido de la cabeza y mi malestar general casi no me dejaban moverme. Aun así empecé a recoger la ropa (casi tan maloliente como yo) y a vestirme, mientras ella no dejaba de preguntarme que porqué me iba tan pronto, que porqué no me quedaba a comer.

Amablemente le dije que muchas gracias, pero que no podía, ya que era tarde y tenía una comida familiar (lógicamente mentira). La uruk-hai se puso un camisón que me recordaba al de Homer en el famoso capítulo en el que aún se pone más gordo y consigue trabajar desde casa. La susodicha (nunca llegué a saber el nombre) estaba algo decepcionada, esperaba que al menos hablase un poco con ella, pero conseguí darle dos besos para despedirme y salir de la habitación.

Al cruzar el pasillo llegué al recibidor junto al salón. Pasé una de las mayores vergüenzas de mi vida cuando me di cuenta de que estaban mirándome, desde el sofá frente al televisor, sus dos compañeras de piso, descojonándose literalmente de mi. Además las dos estaban buenísimas: delgaditas, y una de ellas con el pelo castaño claro y gafitas. Alguna de ellas debería haber sido mi pussy de reencuentro con la soltería... no el manojo de carnes sueltas que me atrapó en sus fauces aquella noche. Lo que me mató fue lo que me soltó la de las gafas:

-¿Anoche jaleito, eh?

Para acto seguido seguir riendo a muerte. Me di la vuelta y salí de aquel piso de infernal recuerdo. Estaba en una tercera planta. Llamé al ascensor, y cuando subí en él, me percaté de mi reflejo en el espejo: mi cara estaba amarilla, las ojeras me llegaban hasta el suelo, el pelo aceitoso se me pegaba a la frente, y tenía un enorme lamparón de vómito en el jersey. Mi estado no podía ser más demigrante.

Salí a la calle y afortunadamente reconocí el sitio: no estaba lejos de mi facultad. Era casi la hora de comer; era domingo: la calle estaba llena de familias felices buscando un sitio de tapas al solecito o un restaurante para comer.

Todos lo vieron: todos vieron el penoso trayecto de un joven derrotado por los azares de la noche y los excesos. Recorrí lo más rápido que pude el camino hacia mi piso. Cuando llegué mis dos compis se estaban zampando una buena olla de spaguetti que por poco vomitan de la risa al verme aparecer. Sin embargo, quien vomitó fui yo justo al llegar al baño. Mis compañeros, sin dejar de descojonarse, me ayudaron a quitarme el jersey, la camisa y los pantalones y me acostaron en mi cama.

Casi no pude conciliar el sueño. "Maldito alcohol", como dice la canción. Más tarde, al despertar, me contaron que en la discoteca no paré de meter mano a todas las mujeres que veía. Que estuvieron a punto de darme de hostias por dicha razón. Que me pedí por lo menos cuatro copas más. Que las derramaba sobre mí al beber. Que finalmente conseguí que una bailara conmigo. Que esa una era el abominable ser que me la estaba chupando al despertar. Que me lié con ella como si fuera la última mujer sobre la faz de la Tierra. Que tenían decenas de fotos de todo (nunca las quise ver, pero se que los cabrones las conservan a buen recaudo).

En fin shurs... esa es mi demigrante confesión. Espero que al menos os haya entretenido. A mi no me hace mucha gracia recordarlo, excepto por lo rotodosiano de la situación al despertar.

Un abrazo y cuidado con lo que hacéis por las noches. ''',
        'insulto':
        '''Me cago en todos los muertos de tu árbol genealógico, y si me apuras también en los vivos, puto amorfo de mierda. Te pillo por la calle y te hundo el pecho a martillazos, enfermo hijo de la gran puta.

Si tienes hijos espero que tengan alguna discapacidad física o mental, o en su defecto los atropelle un autobús. Pero que no mueran, que sufran toda su puta vida, y si no tienes hijos nunca, que será lo que pasará seguramente, Dios te bendiga con una gordaca puto follapinos hijo de la gran puta.

Como me entere de que me reportas otra vez con alguna cuenta así, y me entere de quién eres, te juro que te busco, y cuando te encuentre te voy a ir quitando partes de tu ridículo cuerpo y me las voy a ir comiendo. Mientras me las como las cagaré y te haré comer mis putas heces con trocitos de tu piel rebozados. Cuando ya te haya destripado completamente y te haya hecho comer toda la mierda que suelte de mi precioso y brillante culo iré a por tu hermana, y si no tienes hermana iré a por la sudada de tu puta madre, y si voy inspirado iré a por las dos. Las secuestraré, las meteré en una furgoneta, las llevaré a una habitación, les meteré el rabo por todos los agujeros de su cuerpo (incluidos los de la nariz y orejas), me correré dentro de ellas y esperaré 9 meses a que nazcan sus hijas, y cuando cumplan 13 años me las follaré también.

Y si después de eso te siguen quedando primas o tías, haré lo mismo con ellas, y cuando ya esté cansado de follarme a toda tu familia de piojosos cogeré unas cuantas cadenas, las pondré en mi coche y recorreré 300 km con toda tu familia enganchada a ellas. Si después de eso queda alguien vivo, les echo alcohol para que rabien aún más de dolor.
Después de todo eso, iré al hospital cuando ya te hayas recuperado del destripamiento que te hice. Te sacaré de ahí, te llevaré a la misma habitación donde me follé a todas las mujeres de tu actual familia y a las que preceden en tu árbol genealógico, y mientras te pongo los videos de cómo me follaba a tu madre, te daré minipollazos en la frente hasta que se te quede la marca de mi grande y devastador glande para el resto de tu vida. Así, cada vez que te mires en el espejo, recordarás esos vídeos y lo que hice con tu familia.

Después de eso te soltaré y volveré a ir a por ti a los tres meses. Te volveré a meter en la habitación, pero esta vez nada suave, esta vez cogeré tus manos y empezare a meterte agujas entre las uñas hasta que el nivel de dolor te haga desmayarte y tenga que reanimarte con un desfibrilador. Te bajaré los pantalones y los calzoncillos y empezaré a darte minimartillazos en tus cojones hasta que poco a poco se vayan deshaciendo y tu escroto quede completamente vano.
Imagino que después de eso te desmayarás otra vez, pues volveré a usar el desfibrilador para reanimarte. Meteré tus pies en un cubo con agua, te pondré pinzas en los pezones, pene y lengua y te daré descargas hasta que vuelvas a desmayarte. Cuando lo hagas ya sabes lo que haré, y volveré y cogeré unas tenazas e iré arrancando una a una tus putas uñas pedazo de escoria.

Después te tumbaré, te pondré un trapo en la cara e iré echándote en la boca agua poco a poco sin que llegues a ahogarte.

Después me iré y volveré cada a día para hacerte una tortura diferente, para que cada vez que oigas mis pasos acercándose a la puerta, a horas diferentes de cada día, sientas que un miedo que jamás has experimentado recorra tu cuerpo. Me quedaré en la puerta haciendo como que abro hasta que te mees encima, entonces entraré y comenzaré. Cuando vea que ya no das para más torturas dejaré que te cures en un hospital y volveré a ir a por ti cuando te recuperes. Te cogeré y mientras te quemo los ojos con un soplete te daré martillazos en la nuez hasta que mueras pedazo de hijo de la gran puta.

Pero no pienses que todo acaba ahí. Si la reencarnación existe, volveré reencarnado en cualquier otra persona y te haré a ti y a toda tu nueva familia todo lo que te he hecho en esta vida, pero más lento y sin matarte, para que cada vez que vieses una sombra en la noche pienses que soy yo, para que te entre una locura impresionante y caigas en un estado vegetativo simplemente del miedo que te causa mi presencia. Si te curan, ya no volveré a ir más a por ti, morirás viejo, solo, sin huevos, sin piel y espérate a que no te corte las piernas desecho de mierda. ''',
        'megane':'''esta mañana estabamos unos amigos y yo con las motos por caminos y al cruzar un pueblo perdido nos hemos encontrado un megane pikoletil, y como no tienen nada mejor que hacer, pues nos han dado el alto, algunos han parado menos un hamijo y yo que no hemos parado... Entonces han pasado de los que han parado y nos han seguido durante media hora mas o menos por caminos de mala muerte hasta que han metido las ruedas en una zanja (de lluvia) y les han pegado los bajos brutalmente con el suelo (adios paragolpes delantero y quiza carter) y les hemos dejado ahi tirados... ¡Que bien me he sentido!
PD: ibamos en motos de cross de 250 y 125... ''',
        'megane2':'''A las primeras luces del día, hallábame yo con unas grandes amizades cabalgando los nosos corceles, y, al cruzar do semejaba que nadie habitaba, habémonos encontrado unos miembros de las huestes del Monseñor Renault Megane, concretamente del cuerpo de sus nobles esbirros verdes, los cuales han llevado a cabo su empeño de osar detenernos, lográndolo parcialmente exceptuando a mi y a mi fiel escudero, con el cual hémonos puesto pies en polvorosa. Esto ha causado que aquesas mercedes obcecáranse en su empeño de darnos caza faltando a sus nobles menesteres, entrando en persecución por al menos hasta que el sol se detuviese en lo alto; sin embargo, cual pájaro de mal agüero, encallaron sus rieles en vil hoyo en camino, acabando maltrecha su caballería, tras lo cual mi fiel escudero y mi rocín habémonos dado a la fuga. ¡Qué gran felicidad ocasiona en mi vida aquesta aventura!
p.d: íbamos en corceles de pura sangre y salvajes domados por nuestras propias manos... ''',
        'megane3':'''En los albores de la aurora, unos correligionarios y yo con unas magnates cosmonaves ibamos por unas rutas hiper espaciales y al pasar una estación internacional abandonada convergimos con unos cetrinos cosmonautas sobre una Renault Megane los cuales se atrevierib a retenernos captando fragmentariamente a nuestra escuadra, salvo a mi coagente y a mi que nos hemos deslizado por separado. Después los comisionarios nos han acechado por lo menos hasta que los dos soles se alzaban sobre el firmamento por campos de asteroides no obstante, como profecía del oraculo cesaron al fallar sus condensadores de fluzo tras haber impactado con basura espacial, por lo que mi subalterno y yo nos hemos evadido. ¡Gran júbilo me invadió!
p.d: Nos trasladábamos en módulos de cuatro núcleos ''',
        'empalme':'''A ver chaval, te lo voy a explicar, dado que en el fondo me dais pena los que todavía no sabéis de qué va la vida. Mira, verás, un tío empalmado de verdad tiene el nabo pegado al ombligo como una viga de acero. Por eso la tía no tiene más remedio que moverse de adelante hacia atrás, dado que no tiene fuerza para desplazar ese nabo tieso de la barriga del hombre más que unos centímetros, los justos para metérsela e iniciar el cabalgamiento. Claro, tú esto no sabes lo que es porque no la has tenido empalmada en tu vida. A tí, cuando se te empalma (te crees tú que se te empalma) te la pueden mover en todos los sentidos y direcciones como si fuera de goma, claro está. Pero eso es porque aún no has descubierto tu condición manflorita en grado "anal kamikaze". En efecto, llegará el día en que te encuentres con un muchacho curtido, de piel cetrina y que calce un nardo de 24 centímetros, tanto efecto de su bien dotada raza como del hecho de haber ido colgandero toda la vida. En ese momento descubrirás tu verdadera naturaleza y ahí sí, ahí sabrás lo que es una verdadera erección, y se te pegará el nabín al ombligo...bueno, en tu caso al pubis, y comprenderás porqué el movimiento correcto ha de ser de adelante hacia atrás. Pero claro, en ese momento también descubrirás que a Abdul (que así se llamará tu adorado hombre trípode) no le apetece que te pongas encima, sino a cuatro patas para reventarte el orto mientras te llama perra. Y en ese momento, cuando tengas el culo como un bostezo, cuando tu ojete sea una alcachofa almorranera, y cuando tengas miedo de parpadear porque estás tan lleno por dentro que te parece que te va a reventar el tobogán trasero del amor, entonces y sólo entonces, te acordarás de el día que aprendiste en forocoches que tu verdadera vocación es empalarte con nardos morenos por la parte más oscura y profunda de tu ser. ''',
        'amazon':'''El otro dia iba con mi madre por la calle cuando me empieza a decir que le duele el brazo. Lo que me temía, un infarto. Llamo al 112 y me dicen que tardan 25 minutos en llegar. No sabía que hacer con la desesperación así que miré en la agenda y en el primer contacto tenia la atencion al cliente de Amazon asi que llamé y me dijeron que en 10 minutos me enviaban la ambulancia y además una funda para el iphone y dos cajas de cheerios que tenia en la cesta pero que no había acabado de comprar. No había terminado la encuesta de atencion al cliente posterior a la llamada cuando ya llegaba el samur con mi funda y los cheerios y además un protector de pantalla por las molestias.
Un 10 para amazon, mi madre podría haber muerto. ''',
        'vox':'''Pues eso, que entro en el colegio electoral y voy por mi papeleta podemita pero me cruzo con una interventora del PP bastante follable (veintipocos, buen tipo, una 120C de tetas, no fotos) y me dice que por qué voto a los bolivarianos, que me la chupa y voto al PP. Total, que nos vamos a un baño, empieza ahí al tema y aparece la interventora de Ciudadanos, que era un clon de la Arrimadas, se pone to celosa y dice "si yo te la chupo mejor, votas a C's". Empiezan ahí a pelearse por ver quién chupa mejor, yo ya me vuelvo loco, al final me sacan toda la lefa para 3 meses y he salido del baño con tal bloqueo mental que fui a coger la papeleta de IU pero no la veía, así que cogí la primera que tenía más a mano, que resultó ser la de VOX y dije "mira, voto esto que es la suma de los partidos de estas dos y me voy a seguir con el trío".
Al final seguimos y esta noche vamos a repetir. ''',
        'filologo':'''A ver, vamos por partes: primero, te explicas bien, seguramente seas el jodidamente puto amo de la lengua española, seguramente al salir de tu casa todos los filólogos que te encuentres te chuparán la polla, que debe oscilar los 34 cm y medio. Sin embargo, he de decirte que esos 34 cm y medio no tienen puta comparación con lo que me sudan los cojones ahora mismo. Eres un grande, un puto redactor, Jorge Javier Vázquez estaría orgulloso de comparar su libro con tu post, hijo de mil putas, eres enorme, sigue así, pero tampoco te emociones, tú poco a poco, que no digan por ahí que vas de sobrao, tú postea y que la gente hable, ya lo decía Don Quijote ‘’decir lo que queráis que a mi me suda la polla’’, pues eso. Tú a tu rollo, y si te dicen que tu post es una mierda, ni puto caso. Tienes mis 10 o mis 11, o mis 34 y medio si insistes. ''',
        'melon destrozado':'''me an robado en el coche y melon destrozado

pues eso que e vajao esta mañana y me encuentro con las 2 puertas como si fuera un abre latas y mi sorpresa¡¡¡¡¡la radio del coche no esta joder si la deje devajo escondia y no mea podio ver nadie miro por todo el coche y encima meloan arañao entero,bien el seguro lo tengo la poliza 10 que entra robo y el robo del radio casset tanbien asta un valor de 200e y mi duda es si me entrara tanbien todo los arañazos que mean echo? ayuda¡¡¡¡¡¡¡¡''',
        'caprabo':'''Estaba sacando al perro cuando de repente oigo que me llaman desde un coche aparcado. Me acerco y un tipo me pregunta si sé dónde está la calle del caprabo. Le respondo que por aquí no hay ningun caprabo, y me dice "pues comeme el nabo ausauuuasahashahahaahahaj".
En esto que me subo al coche, y le empiezo a comer toa la polla, una mamada espectacular. Pues no va el hijo de puta y me dice que la chupo mal? me cague en sus muertos y le lancé al perro contra el coche, que obviamente explotó, y el tío salió volando diciendo algo así como "El team rocket despega de nuevooo" (no lo entendí muy bien).
Todavía estoy flipando, hacía tiempo que no veía un coche tan bonito.''',
        'francesa':'''Qee loccuuuraa estando en la plaza fumando..Me viene una francesa y se pone ablar conmiigooo..Lee ofrezzcoo fumar,Lo aceptaa y me dice yo tengo y me abre el bolsoo y maree..xDD
Me diice su nombreeeOranee me presntoo y coje nos saludamos y cojo y le doy medio picoo jajajja..
coje y me dice soy de santa ponsa..a muy bonitoo todoo.
Seguiimos ablando y coje y me suelta asi por la cara quieres mi numero de telefenoo y digo juraa sinoo??
Venga va ahora vengo tiro pal ciber en un saltoo y cojee y me lo daa y le suelto invitate a unoo!!!
y dice tengo priiisaa y me dicee te doy uno si quierees y le digo ohohoh gracias preciiosaa..Coje se despide teniendo su numero y coje y me suelta el medio pico eyaa mareee..estaba riquiiisimaa se muera mi hijoo maree yave ''',
        'islam':'''De cristiano nada, tu eres musulmán. Menudas inmolaciones haces, hijo de la gran puta. Olvídate del bikini y potencia ese burka tan espectacular que llevas, hijo de una perra infiel. Qué puta envidia me das! 
Cuida un poco la barba y tira a la meca. Ramadam y doners es lo que necesitas para terminar de ser un talibán. Menudo hijo de la gran puta eres, ya quisiera yo ese pedazo de cultura. Cabronazo, hijo de mil putas, te envidio muchísimo. Insisto, cuida un poco el respeto y machaca a los europeos a bombas, con esa actitud puedes convertirlos, cabronazo.
Y a los que dicen que estás loco ni puto caso, son un atajo de demócratas respetuosos que les han comido el tarro y que solo les gusta la libertad. Tu, sin embargo, estás enfermo, hijo de la grandísima puta. Qué suerte tenéis algunos con la religión.''',
        'veves':'''Illos donde está la rareza?

Mi amigo tiene un hermano  de 22 años y lo alivian entre los mienbros de la familia ( padre , madre , hermana mayor de 30 años y el que tiene 25 años ) segun toque una vez a la semana.

Por lo visto lo suelen aliviar los jueves después de rehabilitación y el tonto pregunta todos los días; 

Hoy no es veves?''',
        'exnovia (serio)':'''<b>CANESTEN 31/8/2008</b>
Ya ha pasado un tiempo prudencial que reafirme el "lo hemos dejado" y lo aleje del simple "tenemos problemas". Has sufrido, has llorado, has pasado noches en vela buscando el motivo por el cual no continua esa relación que tu considerabas buena. Un simple "necesito pensar, necesito tiempo, estoy confundida" ha sido suficiente para dar carpetazo a ese periodo de tu vida.
Sabes que es una excusa, que no hay confusión, tiene muy claro lo que quiere, pero no se atreve a decírtelo.

Da igual, lo dejas atrás. Sales, te diviertes, retomas viejas aficiones, crees que, verdaderamente, lo has superado.
Pero llega esa noche, quedas con los amigos, cena, copas, risas. Todo va bien. Vas al lugar de siempre; hay buen ambiente. Y la ves.

Y toda esa barrera de seguridad que habías creado a tu alrededor se derrumba. Te das cuenta de que, a pesar de todo el daño recibido, la sigues queriendo.
Te pregunta "¿Cómo estás?" Bien, por supuesto, no puedes mostrar ni un atisbo de debilidad. Le devuelves la pregunta y te contesta lo mismo. Pero notas que en su respuesta hay sinceridad. Está bien, lo ha superado.
Te sientes como una mierda. Da igual que el local esté lleno de chicas, no puedes, no quieres intentar nada con ninguna. Solo piensas en ella. Tus amigos tratan de ayudarte, te alejan de ella, te animan a atacar a otras chicas. Lo hacen de buena fe, pero no es suficiente. Este es un dolor que te tienes que comer tú solo.

Quieres recuperar el tiempo pasado, el momento en que eras feliz con ella y que no sabes en qué momento perdiste.
Sé sincera, joder, dime la verdad, aunque me haga más daño. Me ayudará a cerrar esta parte de mi vida y me permitirá avanzar hacía un futuro que me haga feliz. No seas egoísta.

Solo es una reflexión con un troll de alguien que no se atreve a dar la cara. Respetad ese anonimato.
Perdón por el tocho.'''
        }

